databases:
  - name: rencewang-wall-rails
    databaseName: rencewang-wall-rails
    user: rencewang
    plan: free

services:
  - type: web
    name: rencewang-wall-rails
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rencewang-wall-rails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
